name: Dev Tests
on:
  workflow_dispatch:
  repository_dispatch:
    types: [dev_push]
  push:

jobs:
  list_all_versions:
    runs-on: ubuntu-latest
    name: List all package versions (including deps).
    steps:
      - uses: actions/checkout@v2
      - id: cache-apt-pkgs
        uses: awalsh128/cache-apt-pkgs-action@dev
        with:
          packages: xdot
          version: ${{ github.run_id }}-${{ github.run_attempt }}-list-all-package-versions
      - name: Verify      
        if: steps.cache-apt-pkgs.outputs.cache-hit != 'false' || steps.cache-apt-pkgs.outputs.all-package-version-list != 'gir1.2-atk-1.0:2.35.1-1ubuntu2,gir1.2-gtk-3.0:3.24.20-0ubuntu1.1,gir1.2-pango-1.0:1.44.7-2ubuntu4,graphviz:2.42.2-3build2,libann0:1.1.2+doc-7build1,libcdt5:2.42.2-3build2,libcgraph6:2.42.2-3build2,libgts-0.7-5:0.7.6+darcs121130-4,libgts-bin:0.7.6+darcs121130-4,libgvc6:2.42.2-3build2,libgvpr2:2.42.2-3build2,liblab-gamut1:2.42.2-3build2,libpangoxft-1.0-0:1.44.7-2ubuntu4,libpathplan4:2.42.2-3build2,python3-cairo:1.16.2-2ubuntu2,python3-gi-cairo:3.36.0-1,xdot:1.1-2'
        run: |
          echo "cache-hit = ${{ steps.cache-apt-pkgs.outputs.cache-hit }}"
          echo "package-version-list = ${{ steps.cache-apt-pkgs.outputs.package-version-list }}"
          echo "all-package-version-list = ${{ steps.cache-apt-pkgs.outputs.all-package-version-list }}"
          exit 1
        shell: bash

  list_versions:
    runs-on: ubuntu-latest
    name: List package versions.
    steps:
      - uses: actions/checkout@v2
      - id: cache-apt-pkgs
        uses: awalsh128/cache-apt-pkgs-action@dev
        with:
          packages: xdot rolldice
          version: ${{ github.run_id }}-${{ github.run_attempt }}-list-package-versions
      - name: Verify
        if: steps.cache-apt-pkgs.outputs.cache-hit != 'false' || steps.cache-apt-pkgs.outputs.package-version-list != 'rolldice:1.16-1build1,xdot:1.1-2'
        run: |
          echo "cache-hit = ${{ steps.cache-apt-pkgs.outputs.cache-hit }}" 
          echo "package-version-list = ${{ steps.cache-apt-pkgs.outputs.package-version-list }}"
          exit 1
        shell: bash

  install:
    runs-on: ubuntu-latest
    name: Install package and cache.
    steps:
      - uses: actions/checkout@v2
      - id: cache-apt-pkgs
        uses: awalsh128/cache-apt-pkgs-action@dev
        with:
          packages: xdot rolldice
          version: ${{ github.run_id }}-${{ github.run_attempt }}
      - name: Verify
        if: steps.cache-apt-pkgs.outputs.cache-hit != 'false'
        run: |
          echo "cache-hit = ${{ steps.cache-apt-pkgs.outputs.cache-hit }}"
          exit 1
        shell: bash

  intall_with_new_version:
    runs-on: ubuntu-latest
    name: Install packages with new version.
    steps:
      - uses: actions/checkout@v2
      - id: cache-apt-pkgs
        uses: awalsh128/cache-apt-pkgs-action@dev
        with:
          packages: xdot rolldice
          version: ${{ github.run_id }}-${{ github.run_attempt }}-new_version
      - name: Verify
        if: steps.cache-apt-pkgs.outputs.cache-hit != 'false'
        run: |
          echo "cache-hit = ${{ steps.cache-apt-pkgs.outputs.cache-hit }}"
          exit 1
        shell: bash

  intall_with_new_version_refresh:
    needs: intall_with_new_version
    runs-on: ubuntu-latest
    name: Refresh installed and cached packages.
    steps:
      - uses: actions/checkout@v2
      - id: cache-apt-pkgs
        uses: awalsh128/cache-apt-pkgs-action@dev
        with:
          packages: xdot rolldice
          version: ${{ github.run_id }}-${{ github.run_attempt }}-new_version
          refresh: true
      - name: Verify
        if: steps.cache-apt-pkgs.outputs.cache-hit != 'true'
        run: |
          echo "cache-hit = ${{ steps.cache-apt-pkgs.outputs.cache-hit }}"
          exit 1
        shell: bash

  restore:
    needs: install
    runs-on: ubuntu-latest
    name: Restore cached packages.
    steps:
      - uses: actions/checkout@v2
      - id: cache-apt-pkgs
        uses: awalsh128/cache-apt-pkgs-action@dev
        with:
          packages: xdot rolldice
          version: ${{ github.run_id }}-${{ github.run_attempt }}
      - name: Verify
        if: steps.cache-apt-pkgs.outputs.cache-hit != 'true'
        run: |
          echo "cache-hit = ${{ steps.cache-apt-pkgs.outputs.cache-hit }}"
          exit 1
        shell: bash

  restore_with_packages_out_of_order:
    needs: install
    runs-on: ubuntu-latest
    name: Restore with packages out of order.
    steps:
      - uses: actions/checkout@v2
      - id: cache-apt-pkgs
        uses: awalsh128/cache-apt-pkgs-action@dev
        with:
          packages: rolldice xdot
          version: ${{ github.run_id }}-${{ github.run_attempt }}
      - name: Verify
        if: steps.cache-apt-pkgs.outputs.cache-hit != 'true'
        run: |
          echo "cache-hit = ${{ steps.cache-apt-pkgs.outputs.cache-hit }}"
          exit 1
        shell: bash

  add_package:
    needs: install
    runs-on: ubuntu-latest
    name: Add another package.
    steps:
      - uses: actions/checkout@v2
      - id: cache-apt-pkgs
        uses: awalsh128/cache-apt-pkgs-action@dev
        with:
          packages: xdot rolldice distro-info-data
          version: ${{ github.run_id }}-${{ github.run_attempt }}
      - name: Verify
        if: steps.cache-apt-pkgs.outputs.cache-hit != 'false'
        run: |
          echo "cache-hit = ${{ steps.cache-apt-pkgs.outputs.cache-hit }}"
          exit 1
        shell: bash

  restore_add_package:
    needs: add_package
    runs-on: ubuntu-latest
    name: Restore added package.
    steps:
      - uses: actions/checkout@v2
      - id: cache-apt-pkgs
        uses: awalsh128/cache-apt-pkgs-action@dev
        with:
          packages: xdot rolldice distro-info-data
          version: ${{ github.run_id }}-${{ github.run_attempt }}
      - name: Verify
        if: steps.cache-apt-pkgs.outputs.cache-hit != 'true'
        run: |
          echo "cache-hit = ${{ steps.cache-apt-pkgs.outputs.cache-hit }}"
          exit 1
        shell: bash

  no_packages:
    runs-on: ubuntu-latest
    name: No packages passed.
    steps:
      - name: Execute
        id: execute
        uses: awalsh128/cache-apt-pkgs-action@dev
        with:
          packages: ""
        continue-on-error: true
      - name: Verify
        if: steps.execute.outcome == 'failure'
        run: exit 0
        shell: bash

  package_not_found:
    runs-on: ubuntu-latest
    name: Package not found.
    steps:
      - name: Execute
        id: execute
        uses: awalsh128/cache-apt-pkgs-action@dev
        with:
          packages: package_that_doesnt_exist
        continue-on-error: true
      - name: Verify
        if: steps.execute.outcome == 'failure'
        run: exit 0
        shell: bash

  version_contains_spaces:
    runs-on: ubuntu-latest
    name: Version contains spaces.
    steps:
      - name: Execute
        id: execute
        uses: awalsh128/cache-apt-pkgs-action@dev
        with:
          packages: xdot
          version: 123 abc
        continue-on-error: true
      - name: Verify
        if: steps.execute.outcome == 'failure'
        run: exit 0
        shell: bash